name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.HOST }}               # IP или доменное имя сервера
          username: ${{ secrets.USERNAME }}       # ваше имя пользователя
          
          # дыхание: Секрет содержит приватный ключ
          
          # Замените пути и команды под ваши нужды
          script: |
            # Перейти в директорию проекта
            cd /home/x/your_stretch

            # Остановить службу gunicorn
            sudo /bin/systemctl stop gunicorn_your_stretch

            # Обновить репозиторий
            git pull origin main

            # Установка зависимостей
            /home/x/.local/bin/poetry install --no-root

            # Миграции базы данных
            /home/x/.local/bin/poetry run python manage.py migrate

            # Обновить файл .env (сюда вставьте все переменные окружения)
            echo "${{ secrets.ENV_FILE }}" > .env

            # Собрать статику
            /home/x/.local/bin/poetry run python manage.py collectstatic --noinput

            # Запустить службу gunicorn
            sudo /bin/systemctl start gunicorn_your_stretch