name: Deploy to VPS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          
          # Не указываем password, используем SSH ключ
          
          # Команды на сервере
          script: |
            # Перейти в нужную директорию
            cd /home/x/your_stretch

            # Останавливаем службу Gunicorn
            sudo systemctl stop gunicorn_your_stretch

            # Обновляем код (если репозиторий уже клонен)
            git pull

            # Установка зависимостей
            /home/x/.local/bin/poetry install --no-root

            # Миграции
            /home/x/.local/bin/poetry run python manage.py migrate

            # Обновляем .env
            echo "${{ secrets.ENV_FILE }}" > .env

            # Собираем статику
            /home/x/.local/bin/poetry run python manage.py collectstatic --noinput

            # Перезапускаем Gunicorn
            sudo systemctl start gunicorn_your_stretch