- name: Deploy to VPS
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.SSH_PRIVATE_KEY }}
    script: |
      cd /home/x/your_stretch
      echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop gunicorn_your_stretch
      git pull
      /home/x/.local/bin/poetry install --no-root
      /home/x/.local/bin/poetry run python manage.py migrate
      echo "${{ secrets.ENV_FILE }}" > .env
      /home/x/.local/bin/poetry run python manage.py collectstatic --noinput
      echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start gunicorn_your_stretch