# Название нашего workflow для отображения в интерфейсе GitHub
name: Deploy to VPS

# Указываем когда запускать - при push в main ветку
on:
  push:
    branches: [ main ]

# Определяем задачи для выполнения 
jobs:
  deploy:
    # Указываем на какой ОС запускать
    runs-on: ubuntu-latest

    steps:
      # Получаем код из репозитория
      - uses: actions/checkout@v3

      # Деплоим на сервер через SSH
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          # Используем секреты из GitHub для подключения
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}

          # Команды выполняемые на сервере
          script: |
            # Переходим в директорию проекта
            cd /home/x/your_stratch

            # Останавливаем службу приложения  (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl stop your_stratch

            # Обновляем код из репозитория (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | git pull

            # Если у вас PIP
            # Активируем виртуальное окружение
            # source venv/bin/activate

            # Обновляем зависимости
            # pip install -r requirements.txt

            # Если у вас Poetry
            /home/x/.local/bin/poetry install --no-root

   # Тут можно добавить команду для создания миграций

            # Создаем файл .env из секрета где записано все его содержимое
            echo "${{ secrets.ENV_FILE }}" > .env

            # Перезапускаем systemd сервис (с sudo и передачей пароля)
            echo "${{ secrets.PASSWORD }}" | sudo -S systemctl start your_stratch